[programs.localnet]
anchor_escrow = "6ErRa5iTigqP1kEZbZEGtfViLMMmubpoVgvkVNSrhWgE"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
# windows wallet path
# wallet = "C:\\Users\\sparky\\.config/solana/id.json"

#mac wallet path
# wallet = "/Users/Sparky/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
