[package]
name = "webserver"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"
serde = { version = "1.0.130", features = ["derive"]} 


[dev-dependencies]
actix-rt = "2.2.0"
