[programs.localnet]
p0001 = "HNvdLeRbKqsiHCGqFWi2GMofZtLLMVdGR7uoaNaJLiNb"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "C:\\Users\\sparky\\.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
